ref:
  build: GRCh38
  release: 112

sampling:
  seed: 18764123
  fractions:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0

vembrane:
  expressions:
    pos: "CHROM, POS"
    impact: >
      {"HIGH": 0, "MODERATE": 1, "LOW": 2, "MODIFIER": 3, NA: NA}[ANN["IMPACT"]]
    vus: >
      int(log10(ANN["gnomad_AF"])), desc(ANN["REVEL"])
  max_in_mem_records:
    - 100000
    - 10000
    - 1000